### ISSUE TITLE
Ошибка проверки обновления Версия 4.3.1.1

### ISSUE THREAD

**Issue by NITDroid1995** [GravitLauncher/Launcher#170]
`2019.02.11 11:31:14 [ERROR] org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/GravitLauncher/Launcher/releases/latest
        at org.kohsuke.github.Requester.parse(Requester.java:646)
        at org.kohsuke.github.Requester.parse(Requester.java:607)
        at org.kohsuke.github.Requester._to(Requester.java:285)
        at org.kohsuke.github.Requester.to(Requester.java:247)
        at org.kohsuke.github.GHRepository.getLatestRelease(GHRepository.java:331)
        at ru.gravit.launchserver.Updater.run(Updater.java:46)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
Caused by: java.net.UnknownHostException: api.github.com
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
        at org.kohsuke.github.Requester.parse(Requester.java:615)
        ... 7 more`

**Comment by Zaxar163** [comment]
![image](https://user-images.githubusercontent.com/35835496/52689192-60e26780-2f6a-11e9-9a2e-d831eb8bd8e7.png)
Интернет проверь. И заработает. Ошибка `об отсутствии интернета`.

**Comment by NITDroid1995** [comment]
Понял принял. Просто возникла спантанно)))
