### ISSUE TITLE
LaunchServer v4.3.3-2 dev ветка ошибка при сохранении settings.bin (несогласованность чтения/записи)

### ISSUE THREAD

**Issue by NITDroid1995** [GravitLauncher/Launcher#176]
При первом старте лаунчера все ок. Далее после игровой сессии и закрытии лаунчера, повторный запуск оборачивается ошибкой.
`2019.02.20 19:40:43 [ERROR] java.lang.RuntimeException: Exception in Application init method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:912)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid file name: '     forge.ja'
        at ru.gravit.utils.helper.VerifyHelper.verify(Unknown Source)
        at ru.gravit.utils.helper.IOHelper.verifyFileName(Unknown Source)
        at ru.gravit.launcher.client.LauncherSettings.read(Unknown Source)
        at ru.gravit.launcher.client.LauncherSettings$$NashornJavaAdapter.read(Unknown Source)
        at ru.gravit.launcher.client.LauncherSettings.load(Unknown Source)
        at ru.gravit.launcher.client.LauncherSettings$$NashornJavaAdapter.load(Unknown Source)
        at jdk.nashorn.internal.scripts.Script$Recompilation$4$190$\^eval\_.init(<eval>:9)
        at ru.gravit.launcher.JSApplication$$NashornJavaAdapter.init(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
        ... 2 more`
При удалении options и settings все запускается. Гравит уже правил тут : 

https://github.com/GravitLauncher/Launcher/commit/a738f7566737ba017b94de4c91411c1ef5e93358
https://github.com/GravitLauncher/Launcher/commit/66f773a8cef89baf83e8b70b2b1ba76431a2cf43
https://github.com/GravitLauncher/Launcher/commit/5d77b9c53ab9153ad1c41b256d6b7bb7245224c8
https://github.com/GravitLauncher/Launcher/commit/67b88bc5938365726258fc85be7352a91cc1cc7b
https://github.com/GravitLauncher/Launcher/commit/fc21e854d3d22f0b316af99ffa2a819c1dd54d7a

Осталось решить вопрос с повторным запуском лаунчера.

**Comment by Zaxar163** [comment]
Мне кажется, что пора это дело на json переводить. Что-то явно где-то не так записывается.

**Comment by NITDroid1995** [comment]
Возможно)

**Comment by Zaxar163** [comment]
Попробуй воспроизводи на разных компах. Ещё 1 такое выкинет - начну думать о переходе на json, просто трудно отлаживаемые ошибки.

**Comment by NITDroid1995** [comment]
На всех 3-х компах одно и тоже

**Comment by NITDroid1995** [comment]
У меня вин10. У двух других людей вин7. У всех одно и тоже. Первый запуск после удаления сетингс норм. А потом второй запуск после закрытия клиента(когда лаунчер создал свои файлы) все. Не стартанет....

**Comment by gravit0** [comment]
Этот баг наблюдается только на dev ветке. Как буду у ноута пофиксю, знаю где проблема

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/637652c1c6046bc36db53598671e4f788c182542
