### ISSUE TITLE
Suppressed: java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#201]
Modulea jarsigner
2019.03.26 21:27:16 [ERROR] java.lang.NullPointerException
        at ru.gravit.launchermodules.jarsigner.SignJarTask.process(SignJarTask.java:40)
        at ru.gravit.launchserver.binary.JARLauncherBinary.build(JARLauncherBinary.java:63)
        at ru.gravit.launchserver.LaunchServer.buildLauncherBinaries(LaunchServer.java:605)
        at ru.gravit.launchserver.command.basic.BuildCommand.invoke(BuildCommand.java:23)
        at ru.gravit.utils.command.CommandHandler.eval(CommandHandler.java:41)
        at ru.gravit.utils.command.CommandHandler.eval(CommandHandler.java:30)
        at ru.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:69)
        at ru.gravit.utils.command.CommandHandler.run(CommandHandler.java:82)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF
                at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
                at ru.gravit.launchermodules.jarsigner.SignerJar.writeManifest(SignerJar.java:367)
                at ru.gravit.launchermodules.jarsigner.SignerJar.finish(SignerJar.java:290)
                at ru.gravit.launchermodules.jarsigner.SignerJar.close(SignerJar.java:257)
                at ru.gravit.launchermodules.jarsigner.SignJarTask.process(SignJarTask.java:43)
                ... 8 more
jarsigner module

**Comment by gravit0** [comment]
Это скорее в репозиторий с модулями. JarSigner нет по умолчанию

**Comment by TheXaver** [comment]
Ну пускай isuues тут останется

**Comment by Zaxar163** [comment]
22db53a
