### ISSUE TITLE
Ошибка при запуске клиента

### ISSUE THREAD

**Issue by BlazeFoxPro** [GravitLauncher/Launcher#208]
2019.04.04 20:27:56 [ERROR] java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: SERVER
        at com.google.gson.Gson.toJson(Unknown Source)
        at com.google.gson.Gson.toJson(Unknown Source)
        at com.google.gson.Gson.toJson(Unknown Source)
        at ru.gravit.launcher.teCHna.teCHNG(Unknown Source)
        at ru.gravit.launcher.tEchOK.TEchXp(Unknown Source)
        at ru.gravit.launcher.TEchZT.TEchXp(Unknown Source)
        at ru.gravit.launcher.TEchZT.TEchXp(Unknown Source)
        at ru.gravit.launcher.TEchqH.request(Unknown Source)
        at jdk.nashorn.internal.scripts.Script$Recompilation$69$2936$\^eval\_.newRequestTask#L:80(<eval>:80)
        at javafx.concurrent.Task$$NashornJavaAdapter.call(Unknown Source)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.concurrent.Task$$NashornJavaAdapter.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.AssertionError: java.lang.NoSuchFieldException: SERVER
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(Unknown Source)
        at com.google.gson.internal.bind.TypeAdapters$30.create(Unknown Source)
        at com.google.gson.Gson.getAdapter(Unknown Source)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(Unknown Source)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Unknown Source)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(Unknown Source)
        at com.google.gson.Gson.getAdapter(Unknown Source)
        at com.google.gson.Gson.toJson(Unknown Source)
        at com.google.gson.Gson.toJsonTree(Unknown Source)
        at com.google.gson.Gson.toJsonTree(Unknown Source)
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(Unknown Source)
        at ru.gravit.launcher.TEChue.TEchXp(Unknown Source)
        at ru.gravit.launcher.TEChue.serialize(Unknown Source)
        at com.google.gson.internal.bind.TreeTypeAdapter.write(Unknown Source)
        ... 18 more
Caused by: java.lang.NoSuchFieldException: SERVER
        at java.lang.Class.getField(Unknown Source)
        ... 32 more

**Comment by gravit0** [comment]
Фикс скоро будет
В качестве временного решения попробуйте отключить proguard

**Comment by gravit0** [comment]
Пофикшено
