### ISSUE TITLE
Поддержка ARM

### ISSUE THREAD

**Issue by kossnikita** [GravitLauncher/Launcher#239]
Выдает при попытке запустить на Armbian выдает
```
java -javaagent:LaunchServer.jar -jar LaunchServer.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: [/usr/java/packages/lib, /usr/lib/arm-linux-gnueabihf/jni, /lib/arm-linux-gnueabihf, /usr/lib/arm-linux-gnueabihf, /usr/lib/jni, /lib, /usr/lib], /tmp/libjansi-32-17433518354366682064.so: /tmp/libjansi-32-17433518354366682064.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
        at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
        at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
        at ru.gravit.utils.helper.LogHelper.<clinit>(LogHelper.java:391)
        at ru.gravit.utils.helper.JVMHelper.checkStackTrace(JVMHelper.java:116)
        at ru.gravit.launchserver.LaunchServer.main(LaunchServer.java:287)
```
H3 Quad-core Cortex-A7
ARMBIAN 5.75 stable Ubuntu 18.04.2 LTS 4.19.25-sunxi
openjdk version "11.0.2"

**Comment by gravit0** [comment]
Удалите библиотеку jansi

**Comment by TheXaver** [comment]
11 jdk? Нужен jdk 8

**Comment by kossnikita** [comment]
> Удалите библиотеку jansi

Удалить из директории librararies архива?

**Comment by TheXaver** [comment]
https://bell-sw.com/pages/liberica_install_guide-8u212 из неплохих jdk

**Comment by gravit0** [comment]
Никаких несовместимостей с ARM нет. Краш выше нужно присылать в репозиторий JAnsi, а не сюда.
Если больше вопросов нет, закрываю.
