### ISSUE TITLE
[DEV] Ошибка при экстренном завершение приложения

### ISSUE THREAD

**Issue by DrAAA-X** [GravitLauncher/Launcher#256]
При нажатии CTRL + C такая ошибка:

```
Exception in thread "Command Thread" org.jline.reader.UserInterruptException
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:648)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:395)
        at ru.gravit.utils.command.JLineCommandHandler.readLine(JLineCommandHandler.java:77)
        at ru.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:99)
        at ru.gravit.utils.command.CommandHandler.run(CommandHandler.java:129)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zaxar163** [comment]
Сейчас добавлю try { } catch. @gravit0 а что он делать должен? Завершать?

**Comment by gravit0** [comment]
Пофикшено

**Comment by DrAAA-X** [comment]
```
2019.05.14 16:51:57 [ERROR] java.io.IOException: org.jline.reader.UserInterruptException
        at ru.gravit.utils.command.JLineCommandHandler.readLine(JLineCommandHandler.java:81)
        at ru.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:99)
        at ru.gravit.utils.command.CommandHandler.run(CommandHandler.java:129)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jline.reader.UserInterruptException
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:648)
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:395)
        at ru.gravit.utils.command.JLineCommandHandler.readLine(JLineCommandHandler.java:78)
        ... 3 more
```
