### ISSUE TITLE
Ping in websocket client 

### ISSUE THREAD

**Issue by DrAAA-X** [GravitLauncher/Launcher#270]
Если подождать некоторое время после запуска лаунчера до сообщения "WebSocket client disconnect", то авторизация становится невозможной. 

`[ERROR] Don't skip Launcher Update 
        at ru.gravit.launcher.request.websockets.StandartClientWebSocketService$RequestFuture.get(Unknown Source)
        at ru.gravit.launcher.request.websockets.StandartClientWebSocketService.sendRequest(Unknown Source)
        at ru.gravit.launcher.request.Request.requestDo(Unknown Source)
        at ru.gravit.launcher.request.Request.request(Unknown Source)
...
`

Недавно была исправлена похожая проблема https://github.com/GravitLauncher/Launcher/commit/e1eaad2cd07369350a2a6158d393311421cc9f5c

**Comment by gravit0** [comment]
Логи Wireshark со всем происходящим обменом. Только так мы сможем это починить

**Comment by gravit0** [comment]
Исправлено
