### ISSUE TITLE
Баг в pro.gravit.launcher.client.ClientLauncher.launch()

### ISSUE THREAD

**Issue by usernameak** [GravitLauncher/Launcher#284]
Вкратце:
Если метод main принимает varargs, а не массив, то происходит краш, типа нельзя прикастовать [Ljava/lang/String; в String
Особенно мешает этот баг при использовании ModLauncher вместо LaunchWrapper (приходится писать обёртку), что необходимо при использовании Forge на версии 1.13.2

**Comment by radioegor146** [comment]
Можете привести пример краша?

**Comment by usernameak** [comment]
```
java.lang.ClassCastException: Cannot cast [Ljava.lang.String; to java.lang.String
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at ru.gravit.launcher.client.ClientLauncher.launch(ClientLauncher.java:275)
	at ru.gravit.launcher.client.ClientLauncher.main(ClientLauncher.java:494)
```
Это на версии 5.0.0b4, но аналогичное и на 5.0.4, т.к. код не изменился.
