### ISSUE TITLE
Срач при обновлении лаунчера (не влияет на функционал)

### ISSUE THREAD

**Issue by WhiteBite** [GravitLauncher/Launcher#328]
При обновлении лаунчера в логе краш. На функционал не влияет, так что не горит. 

`2019.08.30 02:07:13 [ERROR] java.lang.NoClassDefFoundError: org/apache/http/util/EntityUtils
        at org.apache.http.impl.client.CloseableHttpClient.execute(Unknown Source)
        at org.apache.http.impl.client.CloseableHttpClient.execute(Unknown Source)
        at org.apache.http.impl.client.CloseableHttpClient.execute(Unknown Source)
        at pro.gravit.launcher.WhitebITExc.WhItebIteBB(Unknown Source)
        at pro.gravit.launcher.whitEbItepg.update(Unknown Source)
        at pro.gravit.launcher.whitEbItepg.WhItebIteBB(Unknown Source)
        at pro.gravit.launcher.whitEbItepg.WhItebIteBB(Unknown Source)
        at pro.gravit.launcher.WHItebItEaA.request(Unknown Source)
        at jdk.nashorn.internal.scripts.Script$Recompilation$87$3139$\^eval\_.newRequestTask#L:85(<eval>:85)
        at javafx.concurrent.Task$$NashornJavaAdapter.call(Unknown Source)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javafx.concurrent.Task$$NashornJavaAdapter.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.http.util.EntityUtils
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more`

Вот так выглядит сама ошибка.
Версия v5.0.5-1 stable

**Comment by gravit0** [comment]
Во время обновления идёт перезапись JAR/EXE файла. После того как записан хотя бы один байт внутри jvm загрузка классов из него становится недоступной(есстественно почему - файл то больше не валидный zip), отчего и лезут ошибки
