### ISSUE TITLE
Краш на 1.14.4

### ISSUE THREAD

**Issue by ijo42** [GravitLauncher/Launcher#337]
Собрал клиент Fabric 1.14, но с гравитом он работает некорректно. С теми же либами на Tlauncher/MultiMC/Mojang все работает. 
Логи с фабрика -- https://paste.dimdev.org/tosocenode.hs
Логи с ванили 1.14 -- https://paste.dimdev.org/nefudopifa.sql 
***
# Как повторить 
* Заходишь на 1.14.4
* Заходишь в локальный мир
* Жмём сделать скриншот (F2)
* Нажимаем по названию скриншота
* _вылет_
**Должно открывать сам файл скриншота**

**Comment by ijo42** [comment]
Актуально для всех клиентов 1.14.4

**Comment by Zaxar163** [comment]
Причина в моих костылях в агенте. Вечером пушну фикс.

**Comment by ijo42** [comment]
@Zaxar163 после 555c6a6 лаунчер вылетает с
```Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.SecurityException: Invalid StackTraceElement: sun.instrument.InstrumentationImpl
        at pro.gravit.utils.helper.JVMHelper.checkStackTrace(Unknown Source)
        at pro.gravit.launcher.LauncherAgent.premain(Unknown Source)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed```

**Comment by ijo42** [comment]
Исправлено
