### ISSUE TITLE
Недостаток зависимости ClientLaunchCore

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/Launcher#388]
java.lang.RuntimeException: Module DiscordRPC required ClientLauncherCore. ClientLauncherCore not found
at pro.gravit.launcher.AbodeOFleGENDs.ABOdEOfLEGends(Unknown Source)
at pro.gravit.launcher.AbodeOFleGENDs.aBOdEoFLeGends(Unknown Source)

5.1.5-dev.

**Comment by gravit0** [comment]
Fixed
