### ISSUE TITLE
Проблема с авторизацией request

### ISSUE THREAD

**Issue by ww1150** [GravitLauncher/Launcher#415]
Здравствуйте, возникла проблема во время авторизации, выдаёт ошибку:
1) При правильной паре логин/пароль:
```
debug true
2020.10.02 22:07:39 [INFO] Command 'debug true'
2020.10.02 22:07:39 [INFO]  Debug enabled: true
2020.10.02 22:07:39 [INFO]  Stacktrace enabled: true
auth user1 password123
2020.10.02 22:07:51 [INFO] Command 'auth user1 password123'
2020.10.02 22:07:52 [ERROR] OK:user1:0

        at pro.gravit.launchserver.auth.provider.AuthProvider.authError(AuthProvider.java:17)
        at pro.gravit.launchserver.auth.provider.RequestAuthProvider.auth(RequestAuthProvider.java:57)
        at pro.gravit.launchserver.command.auth.AuthCommand.invoke(AuthCommand.java:41)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:38)
        at pro.gravit.utils.command.CommandHandler.evalNative(CommandHandler.java:29)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:19)
        at pro.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:74)
        at pro.gravit.utils.command.CommandHandler.run(CommandHandler.java:101)
        at java.base/java.lang.Thread.run(Thread.java:834)

```
2) При не верной паре логин/пароль:
```
auth user1 password12
2020.10.02 22:17:05 [INFO] Command 'auth user1 password12'
2020.10.02 22:17:05 [ERROR] Incorrect login or password

        at pro.gravit.launchserver.auth.provider.AuthProvider.authError(AuthProvider.java:17)
        at pro.gravit.launchserver.auth.provider.RequestAuthProvider.auth(RequestAuthProvider.java:57)
        at pro.gravit.launchserver.command.auth.AuthCommand.invoke(AuthCommand.java:41)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:38)
        at pro.gravit.utils.command.CommandHandler.evalNative(CommandHandler.java:29)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:19)
        at pro.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:74)
        at pro.gravit.utils.command.CommandHandler.run(CommandHandler.java:101)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
Всё раньше работало, после обновление перестала проходить авторизация

Конфиг AuthProvider:
```json
"auth": {
    "std": {
      "isDefault": true,
      "provider": {
	  "type": "request",
	  "usePermission": false,
	  "url": "https://sitename/authLaunch.php?username=%login%&password=%password%&ip=%ip%",
	  "response": "OK:(?<username>.+):(?<permissions>.+)"
      },
```
Скрипт на сайте (движок XenForo v2.1.10):
```php
<?php
header("Content-Type: text/plain; charset=UTF-8");
 
// Verify login and password
$username = $_GET['username'];
$password = $_GET['password'];
$ip = $_GET['ip'];
if(empty($username) || empty($password)) {
    exit('Empty login or password');
}
 
// Load XenForo core and login service
$dir = dirname(__FILE__);
require_once($dir . '/src/XF.php');
XF::start($dir);
$app = \XF::setupApp('XF\Pub\App');
$loginService = $app->service('XF:User\Login', $username, $ip);
 
// Try authenticate user
$error = null;
$user = $loginService->validate($password, $error);
echo($user ? 'OK:' . $user->username . ':' . 0 : 'Incorrect login or password');
?>
```

**Comment by xDev789** [comment]
"usePermission": false -> "usePermission": true

**Comment by ww1150** [comment]
> "usePermission": false -> "usePermission": true

Увы не помогло, абсолютно та же ошибка

**Comment by microwin7** [comment]
Что выводит в браузере, при запросе через данный скрипт?

**Comment by gravit0** [comment]
Если вы не видите символы - это не значит что их нет. Проверка по маске выполняется строго - любые лишние байты и лаунчер посчитает ответ ошибкой. Убедитесь что кодировка файлов UTF-8 без BOM, а так же в отсутствии символов до и после вашего PHP кода или кода какой либо из ваших библиотек
