### ISSUE TITLE
Проблемы с запуском майнкрафта

### ISSUE THREAD

**Issue by MrYulik** [GravitLauncher/Launcher#442]
Лог:
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
GravitLauncher (fork sashok724's Launcher) Client Launcher v5.1.10-2 stable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021.05.30 11:01:57 [INFO] Reading EC keypair
2021.05.30 11:01:57 [INFO] 25.281-b09
2021.05.30 11:01:59 [INFO]  DirWatcher D:\GalaxyWorld\asset1.7.10
2021.05.30 11:01:59 [INFO]  DirWatcher D:\GalaxyWorld\TechMagic
Exception in thread "main" java.lang.IllegalAccessException: no such method: net.minecraft.launchwrapper.Launch.main(String[])void/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:867)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
	at pro.gravit.launcher.GaLaxywOrlDIwQ.GALAXyWOrLd7Om(Unknown Source)
	at pro.gravit.launcher.GaLaxywOrlDIwQ.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	... 4 more
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
Что делать, я уже 3 часа думаю...

**Comment by egorsgn** [comment]
Ты, блядь, конч? Тебе прямым текстом написано, что нет launchwrapper'a.

**Comment by demon1076** [comment]
> 
> 
> Ты, блядь, конч? Тебе прямым текстом написано, что нет launchwrapper'a.

но суть в том, что launchwrapper есть, но всё равно оно даёт такую ошибку..

**Comment by egorsgn** [comment]
> > 
> > 
> > Ты, блядь, конч? Тебе прямым текстом написано, что нет launchwrapper'a.
> 
> но суть в том, что launchwrapper есть, но всё равно оно даёт такую ошибку..
> 

Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec Ты тупой блядь?

**Comment by demon1076** [comment]
возможно. но повторюсь, launchwrapper есть..

**Comment by egorsgn** [comment]
> возможно. но повторюсь, launchwrapper есть..
> 

Возможно ты е6лан, перечитай мой коммент.

**Comment by gravit0** [comment]
Отсутствует библиотека jopt-simple. Добавьте её в свою папку libraries клиента
