### ISSUE TITLE
Не работает Purpur(Paper fork) 1.16.5 уже с authlib2

### ISSUE THREAD

**Issue by paisendevmc** [GravitLauncher/Launcher#444]
[22:47:39 INFO]: [STDERR]: java.lang.NoSuchMethodError: com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.<init>(Ljava/net/Proxy;)V
[22:47:39 INFO]: [STDERR]:      at com.destroystokyo.paper.profile.PaperAuthenticationService.<init>(PaperAuthenticationService.java:13)
[22:47:39 INFO]: [STDERR]:      at net.minecraft.server.v1_16_R3.Main.main(Main.java:106)
[22:47:39 INFO]: [STDERR]:      at org.bukkit.craftbukkit.Main.main(Main.java:283)
[22:47:39 INFO]: [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:47:39 INFO]: [STDERR]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:47:39 INFO]: [STDERR]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:47:39 INFO]: [STDERR]:      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:47:39 INFO]: [STDERR]:      at io.papermc.paperclip.Paperclip.main(Paperclip.java:58)
[22:47:39 INFO]: [STDERR]:      at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:221)
[22:47:39 INFO]: [STDERR]:      at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:65)

**Comment by gravit0** [comment]
Сборка AuthLib 2 для 1.16.4+
https://launcher.gravit.pro/serverbuild

**Comment by paisendevmc** [comment]
> Сборка AuthLib 2 для 1.16.4+
> https://launcher.gravit.pro/serverbuild

уже authlib2

**Comment by paisendevmc** [comment]
в libraries и в libraries клиента или надо еще куда то?
