### ISSUE TITLE
Проблема с лаунчером сервера

### ISSUE THREAD

**Issue by anymelovgames** [GravitLauncher/Launcher#453]
compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Exception in thread "main" 

Как исправить эту ошыбку

**Comment by IIIeX** [comment]
LaunchServer.jar работает только на Java 11+.

**Comment by microwin7** [comment]
Для сборка Лаунчсервера, а так же его использования, необходима JDK 11 + JavaFX

**Comment by Zaxar163** [comment]
[Документацию читать надо](http://launcher.gravit.pro)
![image](https://user-images.githubusercontent.com/35835496/126521146-d8f5c9dd-cb4d-4cd4-8f52-47cb9076718e.png)
