### ISSUE TITLE
Авторизация под WordPress, версия 5.2.0

### ISSUE THREAD

**Issue by Mastaxys** [GravitLauncher/Launcher#510]
Конфигурация под WP, passwordVerifier указан "type": "phpass".
пытаюсь поставить модуль AdditionalHash.
Так вот с конфигом проблема:
[Конфиг](https://pastebin.com/dUGSmfMQ)
ЗЫ, настройки делаю под свою реальную базу.
выдает ошибку :
14:20:03.450 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.0-1 stable (build #1)
14:20:03.451 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
14:20:03.984 [INFO ] JLine2 terminal enabled
14:20:03.987 [INFO ] Reading LaunchServer config file
14:20:04.020 [INFO ] Reading LaunchServer runtime config file
14:20:04.028 [INFO ] Reading ECDSA keypair
14:20:04.032 [INFO ] Reading RSA keypair
Exception in thread "main" java.lang.NullPointerException: Auth std provider null
at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.java:84)
at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerConfig.java:185)
at pro.gravit.launchserver.LaunchServer.(LaunchServer.java:181)
at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder.java:91)
at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:187)

или этот модуль только для версии 5.1.10? 
без AdditionalHash, но с настроеным passwordVerifier  все равно крашит [дебаглог](https://pastebin.com/FGZd7G1t)

**Comment by gravit0** [comment]
Пожалуйста ВНИМАТЕЛЬНО читайте инструкцию. Для core необходимо изменить только passwordVerifier, менять тип у core не нужно
Модуль у вас должен быть от 5.2.0, который находится в архиве рядом с лаунчсервером

**Comment by Mastaxys** [comment]
Так? https://pastebin.com/DnikRyCY
так всё равно крашит

**Comment by gravit0** [comment]
На Вики написано как правильно
