### ISSUE TITLE
Краш клиента fabric 1.17.1 при автовходе

### ISSUE THREAD

**Issue by ShitryaDima** [GravitLauncher/Launcher#511]
Не работает автовход в лаунчере, если запускаться и заходить на сервер без него, то всё нормально, но когда с ним, то клиент крашится во время загрузки. Если смотреть в консоль сервера, то пишется, что игрок вошёл на сервер и сразу же вышел.
Краш репорт клиента:
```---- Minecraft Crash Report ----
// My bad.
 
Time: 8/22/21, 2:33 AM
Description: Unexpected error
 
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null
    at net.minecraft.class_636.method_2911(class_636.java:292)
    at net.minecraft.class_636.method_2927(class_636.java:271)
    at net.minecraft.class_310.method_1574(class_310.java:1698)
    at net.minecraft.class_310.method_1523(class_310.java:1081)
    at net.minecraft.class_310.method_1514(class_310.java:728)
    at net.minecraft.client.main.Main.main(Main.java:217)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
    at pro.gravit.launcher.SpRingcraFtSAY.SpriNgCrAFT6UN(Unknown Source)
    at pro.gravit.launcher.SpRingcraFtSAY.main(Unknown Source)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
    at net.minecraft.class_636.method_2911(class_636.java:292)
    at net.minecraft.class_636.method_2927(class_636.java:271)
 
-- Affected level --
Details:
    All players: 0 total; []
    Chunk stats: 1024, 625
    Level dimension: minecraft:overworld
    Level spawn location: World: (160,72,-255), Section: (at 0,8,1 in 10,4,-16; chunk contains blocks 160,0,-256 to 175,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 28249 game time, 2332249 day time
    Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.class_638.method_8538(class_638.java:370)
    at net.minecraft.class_310.method_1587(class_310.java:2399)
    at net.minecraft.class_310.method_1514(class_310.java:752)
    at net.minecraft.client.main.Main.main(Main.java:217)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:567)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
    at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
    at pro.gravit.launcher.SpRingcraFtSAY.SpriNgCrAFT6UN(Unknown Source)
    at pro.gravit.launcher.SpRingcraFtSAY.main(Unknown Source)
 
-- Last reload --
Details:
    Reload number: 1
    Reload reason: initial
    Finished: No
    Packs: Default, Fabric Mods
 
-- System Details --
Details:
    Minecraft Version: 1.17.1
    Minecraft Version ID: 1.17.1
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 16.0.2, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
    Memory: 302058152 bytes (288 MiB) / 1006632960 bytes (960 MiB) up to 2147483648 bytes (2048 MiB)
    CPUs: 4
    Processor Vendor: GenuineIntel
    Processor Name: Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
    Identifier: Intel64 Family 6 Model 94 Stepping 3
    Microarchitecture: unknown
    Frequency (GHz): 3.70
    Number of physical packages: 1
    Number of physical CPUs: 2
    Number of logical CPUs: 4
    Graphics card #0 name: Intel(R) HD Graphics 530
    Graphics card #0 vendor: Intel Corporation (0x8086)
    Graphics card #0 VRAM (MB): 1024.00
    Graphics card #0 deviceId: 0x1912
    Graphics card #0 versionInfo: DriverVersion=27.20.100.9126
    Memory slot #0 capacity (MB): 4096.00
    Memory slot #0 clockSpeed (GHz): 2.13
    Memory slot #0 type: DDR4
    Memory slot #1 capacity (MB): 4096.00
    Memory slot #1 clockSpeed (GHz): 2.13
    Memory slot #1 type: DDR4
    Virtual memory max (MB): 24157.42
    Virtual memory used (MB): 14480.05
    Swap memory total (MB): 16078.71
    Swap memory used (MB): 1066.71
    JVM Flags: 6 total; -XX:+DisableAttachMechanism -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    Fabric Mods: 
        fabric: Fabric API 0.36.1+1.17
        fabric-api-base: Fabric API Base 0.3.0+a02b446313
        fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
        fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
        fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
        fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
        fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
        fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
        fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
        fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
        fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
        fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
        fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
        fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
        fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
        fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
        fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
        fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
        fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
        fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
        fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
        fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
        fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
        fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
        fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
        fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
        fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
        fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
        fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
        fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
        fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
        fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
        fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b4463d5
        fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
        fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c13
        fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
        fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
        fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
        fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
        fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
        fabricloader: Fabric Loader 0.11.6
        iris: Iris 1.1.1
        java: Java HotSpot(TM) 64-Bit Server VM 16
        minecraft: Minecraft 1.17.1
        plasmo_voice: Plasmo Voice 1.0.10
        sodium: Sodium 0.3.0+IRIS2
    Launched Version: 1.17.1
    Backend library: LWJGL version 3.2.2 build 10
    Backend API: Intel(R) HD Graphics 530 GL version 3.2.0 - Build 27.20.100.9126, Intel
    Window size: 854x480
    GL Caps: Using framebuffer using OpenGL 3.2
    GL debug messages: 
    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fabric'
    Type: Client (map_client.txt)
    Graphics mode: fancy
    Resource Packs: vanilla, Fabric Mods
    Current Language: English (US)
    CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz```

**Comment by dimadencep** [comment]
Это проблема не лаунчера, а твоей тупой головы

**Comment by dimadencep** [comment]
Закройте этот репорт

**Comment by ShitryaDima** [comment]
Жду адекватного ответа от нормального человека

**Comment by JoCat** [comment]
Могу конечно ошибаться, но это вроде баг майна (либо клиентов с модлоадерами)

**Comment by egorsgn** [comment]
у тебя NPE, логично что проблема в клиенте и он вызывает нулл в каком то месте

**Comment by JoCat** [comment]
> > Могу конечно ошибаться, но это вроде баг майна (либо клиентов с модлоадерами)
> 
> Да, мне кто-то говорил, что это баг клиентов с модлоадерами, но может существует какая-то возможность исправить это?

Хз, к слову возможно это пошло с сашка и дошло до сюда, но ма моём лаунчере автозаход работает корректно 😅

**Comment by Zaxar163** [comment]
В одном из ТЛ тоже было :(

**Comment by FluffyCuteOwO** [comment]
Может уже стоит закрыть это чудо?

**Comment by JoCat** [comment]
> Может уже стоит закрыть это чудо?

Да, пожалуй пора закрывать гравит 🤣
