### ISSUE TITLE
проблема с авторизации

### ISSUE THREAD

**Issue by yuliitezary** [GravitLauncher/Launcher#537]
10:11:35.808 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.6-1 stable (build #1)
10:11:35.816 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
10:11:36.298 [INFO ] JLine2 terminal enabled
10:11:36.299 [INFO ] Reading LaunchServer config file
10:11:36.340 [INFO ] Reading LaunchServer runtime config file
10:11:36.420 [INFO ] Reading ECDSA keypair
10:11:36.424 [INFO ] Reading RSA keypair
Exception in thread "main" java.lang.NullPointerException: AuthProviderPair`s count should be at least one
        at pro.gravit.launchserver.config.LaunchServerConfig.verify(LaunchServerConfig.java:150)
        at pro.gravit.launchserver.LaunchServer.<init>(LaunchServer.java:151)
        at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder.java:91)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:183)
Для продолжения нажмите любую клавишу . . .

![изображение](https://user-images.githubusercontent.com/94526027/144196418-57672465-c1e1-4a34-8b15-d5325839e66f.png)

**Comment by gravit0** [comment]
В конфиге должен быть указан хотя бы один AuthProviderPair(секция auth не существует или пуста)

**Comment by yuliitezary** [comment]
> 

![изображение](https://user-images.githubusercontent.com/94526027/144197350-5bffad07-300d-4c51-8efd-a60ccd0914a1.png)
10:18:40.697 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.6-1 stable (build #1)
10:18:40.701 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
10:18:41.303 [INFO ] JLine2 terminal enabled
10:18:41.330 [INFO ] Reading LaunchServer config file
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 45 column 23 path $.auth.
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:963)
        at com.google.gson.Gson.fromJson(Gson.java:901)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:118)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 45 column 23 path $.auth.
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        ... 8 more
Для продолжения нажмите любую клавишу . . .
