### ISSUE TITLE
при хапуске маинкрафт такая ошыбка в консоле 

### ISSUE THREAD

**Issue by yuliitezary** [GravitLauncher/Launcher#540]
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

и в дебуг от лаунчера 
GravitLauncher (fork sashok724's Launcher) Client Launcher v5.2.6-1 stable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021.12.02 18:35:31 [WARN] JLine2 isn't in classpath, using std
2021.12.02 18:35:31 [INFO] Reading EC keypair
2021.12.02 18:35:31 [INFO] Using Sessions
2021.12.02 18:35:31 [INFO] 25.311-b11
2021.12.02 18:35:32 [INFO]  DirWatcher C:\Users\Admin\Desktop\games\asset1.12.2
2021.12.02 18:35:32 [INFO]  DirWatcher C:\Users\Admin\Desktop\games\HiTech
2021-12-02 18:35:34,804 main WARN Plugin [terminalconsole] is already mapped to class net.minecraftforge.server.console.log4j.TerminalConsoleAppender, ignoring class net.minecraftforge.server.console.TerminalConsoleAppender
2021-12-02 18:35:35,052 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2021-12-02 18:35:35,117 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-12-02 18:35:35,187 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[18:35:35] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[18:35:35] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[18:35:35] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:35:35] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[18:35:35] [main/INFO]: Bootstrapping LiteLoader 1.12.2
2021-12-02 18:35:35,456 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-12-02 18:35:35,493 main WARN Plugin [terminalconsole] is already mapped to class net.minecraftforge.server.console.log4j.TerminalConsoleAppender, ignoring class net.minecraftforge.server.console.TerminalConsoleAppender
2021-12-02 18:35:35,496 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2021-12-02 18:35:35,500 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-12-02 18:35:35,516 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[18:35:35] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[18:35:35] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[18:35:35] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[18:35:35] [main/INFO]: Initialising API 'liteloader' ...
[18:35:35] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/C:/Users/Admin/Desktop/games/HiTech/liteloader.jar Service=LaunchWrapper Env=CLIENT
[18:35:35] [main/INFO]: LiteLoader begin PREINIT...
[18:35:35] [main/INFO]: Initialising Loader properties...
[18:35:35] [main/INFO]: Setting up logger...
[18:35:35] [main/INFO]: LiteLoader 1.12.2 starting up...
[18:35:35] [main/INFO]: Active Pack: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
[18:35:35] [main/INFO]: Java reports OS="windows 10"
[18:35:35] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[18:35:35] [main/INFO]: Enumerating class path...
[18:35:35] [main/INFO]: Class path separator=";"
[18:35:35] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\Admin\Desktop\Launcher.exe
)
[18:35:35] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[18:35:35] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Admin\Desktop\games\HiTech\mods]
[18:35:35] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Admin\Desktop\games\HiTech\mods\1.12.2]
[18:35:35] [main/INFO]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@4e8e8621]
[18:35:36] [main/INFO]: Discovering valid mod files in folder C:\Users\Admin\Desktop\games\HiTech\mods
[18:35:36] [main/INFO]: Discovering valid mod files in folder C:\Users\Admin\Desktop\games\HiTech\mods\1.12.2
[18:35:36] [main/INFO]: Inspecting jar metadata in 'OptiFine_1.12.2_HD_U_D3.jar'
[18:35:36] [main/INFO]: Baking listener list for EnumerationObserver with 1 listeners
[18:35:36] [main/INFO]: Discovering tweaks on class path...
[18:35:36] [main/INFO]: Registering discovered mod files in folder C:\Users\Admin\Desktop\games\HiTech\mods
[18:35:36] [main/INFO]: Registering discovered mod files in folder C:\Users\Admin\Desktop\games\HiTech\mods\1.12.2
[18:35:36] [main/INFO]: Mod file 'OptiFine_1.12.2_HD_U_D3.jar' provides tweakClass 'optifine.OptiFineForgeTweaker', adding to Launch queue with priority -1000
[18:35:36] [main/INFO]: tweakClass 'optifine.OptiFineForgeTweaker' was successfully added
[18:35:36] [main/INFO]: ClassPathUtilities: attempting to inject file:/C:/Users/Admin/Desktop/games/HiTech/mods/1.12.2/OptiFine_1.12.2_HD_U_D3.jar into LaunchClassLoader
[18:35:36] [main/INFO]: Initialising LiteLoader Mixins
[18:35:36] [main/INFO]: Compatibility level set to JAVA_8
[18:35:36] [main/INFO]: LiteLoader PREINIT complete
[18:35:36] [main/INFO]: Injecting cascaded tweakers...
[18:35:36] [main/INFO]: Injecting tweak class optifine.OptiFineForgeTweaker with priority -1000
[18:35:36] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[18:35:36] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[18:35:36] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[18:35:36] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[18:35:36] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[18:35:36] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[18:35:36] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
2021.12.02 18:35:36 [ERROR] java.lang.NoClassDefFoundError: com/mojang/authlib/exceptions/AuthenticationException
JVM exit code 0
2021.12.02 18:35:36 [INFO] WebSocket client disconnect
Process exit code 0

**Comment by LaymQ** [comment]
Внимательно читайте установку и настройку клиента. У вас не хватает библиотеки "authlib"

**Comment by LaymQ** [comment]
Так же откройте порт 9274

**Comment by yuliitezary** [comment]
> Так же откройте порт 9274, для работы ЛаунчСервера

порты открыты и где взяти библиотеку

**Comment by LaymQ** [comment]
Почитайте тут [http://launcher.gravit.pro/clientbuild#authlib1](url)

**Comment by yuliitezary** [comment]
> Почитайте тут [http://launcher.gravit.pro/clientbuild#authlib1](url)

![изображение](https://user-images.githubusercontent.com/94526027/144467579-69254972-0ea5-455e-a743-845d3c79ceb0.png)
где

**Comment by LaymQ** [comment]
Прочитайте тут http://launcher.gravit.pro/clientbuild#authlib1
