### ISSUE TITLE
SpongeAPI not found

### ISSUE THREAD

**Issue by Engrems** [GravitLauncher/Launcher#564]
Всем привет, столкнулся с проблемой, что при запуске сервера 1.12.2(пробовал на магме и на мохисте) через ServerWrapper возникает непонятная мне ошибка с губкой, дак в этой ошибке еще и учавствует критично важный мне eventhelper от gamerforea -- фиксы для модов. Запуск через start.sh эту ошибку убирает -- я полагаю, это баг в гравите. Конфиги враппера и стартер я укажу ниже, так же как и ошибку саму. Я отдаю себе отчёт, что это может быть из-за моих рук, которые могли расти в ненужном направлении в какой-то момент, но всё же ожидаю совета или помощи от неравнодушних людей :)

PS: один и тот же сервер при запуске через гравит выдают эту ошибку, а при запуске обычном - работает замечательно, никаких других проблем с лаунчером/сервером нет. Заранее всем спасибо за участие.

-----------------------------------------------------

ServerWrapper КОНФИГ

{
  "projectname": "Apleng",
  "address": "тут адрес ws://",
  "serverName": "Apocalypse",
  "autoloadLibraries": false,
  "classpath": [],
  "mainclass": "com.mohistmc.MohistMC",
  "args": [],
  "oauthExpireTime": 0,
  "extendedTokens": {
    "checkServer": "тут токен"
  },
  "env": "STD"
}

-----------------------------------------------------

START.SH который не вызывает ошибку
#!/bin/bash

/usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp ServerWrapper.jar:core_m.jar pro.gravit.launcher.server.ServerWrapper

-----------------------------------------------------

строка запуска, которая вызывает ошибку

/usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp ServerWrapper.jar:core_m.jar pro.gravit.launcher.server.ServerWrapper

-----------------------------------------------------

ОШИБКА:

SpongeAPI not found
 java.lang.ClassNotFoundException: org.spongepowered.api.Server
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:189) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_312]
        at com.gamerforea.eventhelper.integration.sponge.SpongeIntegration.<clinit>(SpongeIntegration.java:62) [SpongeIntegration.class:?]
        at com.gamerforea.eventhelper.util.EventUtils.<clinit>(EventUtils.java:172) [EventUtils.class:?]
        at com.gamerforea.eventhelper.fake.FakePlayerContainer.cantBreak(FakePlayerContainer.java:140) [FakePlayerContainer.class:?]
        at appeng.parts.automation.PartAnnihilationPlane.breakBlock(PartAnnihilationPlane.java:384) [PartAnnihilationPlane.class:?]
        at appeng.parts.automation.PartAnnihilationPlane.call(PartAnnihilationPlane.java:95) [PartAnnihilationPlane.class:?]
        at appeng.parts.automation.PartAnnihilationPlane.call(PartAnnihilationPlane.java:71) [PartAnnihilationPlane.class:?]
        at appeng.hooks.TickHandler.processQueue(TickHandler.java:192) [TickHandler.class:?]
        at appeng.hooks.TickHandler.onTick(TickHandler.java:169) [TickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_890_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:96) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:283) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException

**Comment by dimadencep** [comment]
Проблема не в лаунчере, обратитесь к поддержке sponge или автору мода/плагина который вызывает проблему

**Comment by Engrems** [comment]
Повторюсь, проблема проявляет себя исключительно с гравитом, на любых ядрах/сборках такой ошибки нет. Ядро не спонж, а мод просит спонж, но при этом только если установлен на гравит. Если есть хоть малейшая вероятность, что в гравите дело, то мне кажется - это оно. Прошу повторного ответа :) Готов предоставить любые логи

**Comment by Engrems** [comment]
> Проблема не в лаунчере, обратитесь к поддержке sponge или автору мода/плагина который вызывает проблему
Повторюсь, проблема проявляет себя исключительно с гравитом, на любых ядрах/сборках такой ошибки нет. Ядро не спонж, а мод просит спонж, но при этом только если установлен на гравит. Если есть хоть малейшая вероятность, что в гравите дело, то мне кажется - это оно. Прошу повторного ответа :) Готов предоставить любые логи
