### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by Khikki** [GravitLauncher/Launcher#574]
Здравствуйте, прошу помощи так как не могу понять в чём ошибка, когда собираю тестовый exe-ник выпадает ошибка, подскажите пожалуйста :)

Полный лог: https://gist.github.com/Khikki/d54dab221d67b5416467cd35ed843676

Ошибка: 
```18:24:51.730 [ERROR] java.io.IOException: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (2): /home/launcher/gravit/src/LaunchServer/build/libs/libraries/launch4j/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j1642740782183222385rc /tmp/launch4j4147004417693167233o
	at pro.gravit.launchserver.binary.tasks.exe.Launch4JTask.process(Launch4JTask.java:57)
	at pro.gravit.launchserver.binary.BinaryPipeline.build(BinaryPipeline.java:85)
	at pro.gravit.launchserver.binary.LauncherBinary.build(LauncherBinary.java:26)
	at pro.gravit.launchserver.LaunchServer.buildLauncherBinaries(LaunchServer.java:282)
	at pro.gravit.launchserver.command.basic.BuildCommand.invoke(BuildCommand.java:23)
	at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:38)
	at pro.gravit.utils.command.CommandHandler.evalNative(CommandHandler.java:29)
	at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:19)
	at pro.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:74)
	at pro.gravit.utils.command.CommandHandler.run(CommandHandler.java:101)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (2): /home/launcher/gravit/src/LaunchServer/build/libs/libraries/launch4j/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j1642740782183222385rc /tmp/launch4j4147004417693167233o
	at net.sf.launch4j.Builder.build(Builder.java:149)
	at pro.gravit.launchserver.binary.tasks.exe.Launch4JTask.process(Launch4JTask.java:55)
	... 10 more
Caused by: net.sf.launch4j.ExecException: Exec failed (2): /home/launcher/gravit/src/LaunchServer/build/libs/libraries/launch4j/bin/windres --preprocessor=cat -J rc -O coff -F pe-i386 /tmp/launch4j1642740782183222385rc /tmp/launch4j4147004417693167233o
	at net.sf.launch4j.Util.exec(Util.java:156)
	at net.sf.launch4j.Cmd.exec(Builder.java:215)
	at net.sf.launch4j.Builder.build(Builder.java:100)
	... 11 more

**Comment by microwin7** [comment]
Установите другую JDK
![image](https://user-images.githubusercontent.com/12544425/163608911-02a0b4c6-4411-4c67-a1ed-f6f032d68855.png)
```
sudo apt-get update ; sudo apt-get install gnupg2 wget apt-transport-https -y ; wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add - ; echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list ; sudo apt-get update ; sudo apt-get install -y bellsoft-java17-full
```

```
sudo update-alternatives --config java
```

**Comment by Khikki** [comment]
Выпадает ошибка: ```E: Unable to locate package bellsoft-java17-full```

**Comment by Khikki** [comment]
Кто-нибудь может подсказать? ;с

**Comment by Khikki** [comment]
https://gist.github.com/Khikki/467806ed6dff655730bf7e35b1b2d958

**Comment by Khikki** [comment]
Проблема была в архитектуре процессора, пытались собрать на arm (aarch), вдруг кто-либо столкнётся.

**Comment by microwin7** [comment]
> Проблема была в архитектуре процессора, пытались собрать на arm (aarch), вдруг кто-либо столкнётся.

Об этом сразу бы сказали мы, если бы уточнили. Ну да, exe не собрать никак
