### ISSUE TITLE
ServerWrapper при запуске 

### ISSUE THREAD

**Issue by yuliitezary** [GravitLauncher/Launcher#575]
Exception in thread "main" java.lang.NoSuchMethodError: org.fusesource.jansi.Ansi.fgBright(Lorg/fusesource/jansi/Ansi$Color;)Lorg/fusesource/jansi/Ansi;
        at pro.gravit.utils.helper.FormatHelper.ansiFormatVersion(FormatHelper.java:58)
        at pro.gravit.utils.logging.Slf4jLogHelperImpl.printVersion(Slf4jLogHelperImpl.java:106)
        at pro.gravit.utils.helper.LogHelper.printVersion(LogHelper.java:144)
        at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:58)

**Comment by Frysuni** [comment]
Добавьте параметр -Dlauncher.noJAnsi=true к аргументам JVM
