### ISSUE TITLE
Ошибка java.lang.InstantiationException: Error on instancing...

### ISSUE THREAD

**Issue by mavvist** [GravitLauncher/Launcher#577]
Появилась при запуске после установки рантайма

```
11:45:41.436 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.11-1 stable (build #1)
11:45:41.437 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
11:45:41.582 [ERROR] java.lang.InstantiationException: Error on instancing...
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.loadModule(SimpleModuleManager.java:162)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager$ModulesVisitor.visitFile(SimpleModuleManager.java:279)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager$ModulesVisitor.visitFile(SimpleModuleManager.java:272)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
        at pro.gravit.utils.helper.IOHelper.walk(IOHelper.java:588)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.autoload(SimpleModuleManager.java:67)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.autoload(SimpleModuleManager.java:61)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:88)
Caused by: java.lang.IllegalAccessException: no such constructor: pro.gravit.launcher.client.JavaRuntimeModule.<init>()void/newInvokeSpecial
        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:972)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.loadModule(SimpleModuleManager.java:159)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: pro/gravit/launcher/gui/RuntimeProvider
        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: pro.gravit.launcher.gui.RuntimeProvider
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 13 more

11:45:41.584 [ERROR] In module C:\Users\MAVIST\Desktop\launcher\modules\JavaRuntime_lmodule.jar Module-Main-Class incorrect
11:45:41.805 [INFO ] JLine2 terminal enabled
11:45:41.806 [INFO ] Reading LaunchServer config file
11:45:41.840 [INFO ] Reading LaunchServer runtime config file
11:45:41.881 [INFO ] Reading ECDSA keypair
11:45:41.886 [INFO ] Reading RSA keypair
11:45:42.011 [INFO ] Syncing launcher binaries
11:45:42.012 [INFO ] Syncing launcher binary file
11:45:42.097 [INFO ] Syncing launcher EXE binary file
11:45:42.130 [DEBUG] Init components
11:45:42.132 [DEBUG] Init component regLimiter
11:45:42.134 [DEBUG] Init component authLimiter
11:45:42.136 [DEBUG] Init component proguard
11:45:42.139 [DEBUG] Init components successful
11:45:42.147 [INFO ] LaunchServer started
11:45:42.149 [INFO ] Starting netty server socket thread
11:45:42.154 [DEBUG] Found 0 updates from cache
11:45:42.159 [INFO ] Syncing profiles dir
```

**Comment by microwin7** [comment]
Модуль рантайма находится в папке модулей лаунчсервера, а должен быть в папке модулей лаунчера
launcher-modules

**Comment by mavvist** [comment]
> Модуль рантайма находится в папке модулей лаунчсервера, а должен быть в папке модулей лаунчера launcher-modules

Сделал, ошибка ушла, но про компиляции не запускается exe

**Comment by mavvist** [comment]
Решил вторую проблему сам, спасибо за помощь по тикету!
