### ISSUE TITLE
При настройке авторизации AuthCoreProvider в консоли.

### ISSUE THREAD

**Issue by Sashok2007** [GravitLauncher/Launcher#584]
18:58:13.940 [WARN ] Replace mirror 'https://mirror.gravit.pro/' to 'https://mir/
ror.gravit.pro/5.2.x/'. If you really need to use original url, use '-Dlaunchser
ver.config.disableUpdateMirror=true'
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pro.gr
avit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.Launch
Server)" because "this.core" is null
at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.j
ava:77)
at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerCo
nfig.java:183)
at pro.gravit.launchserver.LaunchServer.(LaunchServer.java:159)
at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder
.java:91)
at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.
java:182)
Для продолжения нажмите любую клавишу . . .

**Comment by Sashok2007** [comment]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pro.gr
avit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.Launch
Server)" because "this.core" is null
        at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.j
ava:77)
        at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerCo
nfig.java:183)
        at pro.gravit.launchserver.LaunchServer.<init>(LaunchServer.java:159)
        at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder
.java:91)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.
java:182)
Для продолжения нажмите любую клавишу . . .
