### ISSUE TITLE
Ошибка при настройке Gravit Launcher

### ISSUE THREAD

**Issue by qourshi** [GravitLauncher/Launcher#589]
Пытаюсь настроить Gravit Launcher по тутору из Wiki. (для Windows)
Но ошибка за ошибкой плывут мне в консоль.

Exception in thread "main" java.lang.RuntimeException: Module OneLauncher required ClientLauncherCore. ClientLauncherCore not found
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.checkDepend(SimpleModuleManager.java:109)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.initModules(SimpleModuleManager.java:82)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:89)

**Comment by Frysuni** [comment]
Модули _module надо ставить в папку modules.
Модули _lmodule надо ставить в папку launcher-modules. 
По таким проблемам обращайтесь на Дискорд сервер гравитлаунчера. Тикет закройте.

**Comment by qourshi** [comment]
В вашем wiki не полно описан процесс установки под Windows, я запутался и теперь мучаюсь с другой ошибкой. Спасибо
