### ISSUE TITLE
Ошибка при запуске start server с модулями ClientLauncherCore not found

### ISSUE THREAD

**Issue by MiFliK** [GravitLauncher/Launcher#592]
09:42:03.241 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.12-1 stable (build #1)
09:42:03.242 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
Exception in thread "main" java.lang.RuntimeException: Module OneLauncher required ClientLauncherCore. ClientLauncherCore not found
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.checkDepend(SimpleModuleManager.java:109)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.initModules(SimpleModuleManager.java:82)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:89)

**Comment by gravit0** [comment]
Модуль OneLauncher устанавливается в папку launcher-modules, как и все модули заканчивающиеся на `_lmodule`
