### ISSUE TITLE
Не хочет запускать LaunchServer

### ISSUE THREAD

**Issue by KaizersokVGC** [GravitLauncher/Launcher#594]
ОС Debian 11

launcher@vincit:~$ ./start.sh
21:04:44.163 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.                                                                                                             2.12-1 stable (build #1)
21:04:44.164 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.                                                                                                             com/GravitLauncher/Launcher
21:04:44.574 [INFO ] JLine2 terminal enabled
21:04:44.576 [INFO ] Reading LaunchServer config file
Exception in thread "main" com.google.gson.JsonSyntaxException: java.nio.charset                                                                                                             .MalformedInputException: Input length = 1
        at com.google.gson.Gson.fromJson(Gson.java:1006)
        at com.google.gson.Gson.fromJson(Gson.java:929)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.                                                                                                             java:117)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.jav                                                                                                             a:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
        at java.base/java.io.BufferedReader.read1(BufferedReader.java:213)
        at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1290)
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1                                                                                                             328)
        at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.                                                                                                             java:1605)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:534)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.Gson.fromJson(Gson.java:987)
        ... 2 more
launcher@vincit:~$ ^C
launcher@vincit:~$

**Comment by KaizersokVGC** [comment]
![Screenshot_168](https://user-images.githubusercontent.com/105551614/174494626-20e5e6fd-0c7d-4f40-82d7-bc9bf91236db.png)

**Comment by microwin7** [comment]
Сломан файл LaunchServer.json

**Comment by KaizersokVGC** [comment]
Хорошо, ещё один вопрос: при установке лаунчера на VDS надо писать ip/ip+порт или localhost? Я немножко чайник

**Comment by KaizersokVGC** [comment]
OpenJFX установил, а он его всё ещё не видит(

**Comment by PadowYT2** [comment]
ip либо ip+port твое решение
