### ISSUE TITLE
Проблема с authlib

### ISSUE THREAD

**Issue by ccyounga** [GravitLauncher/Launcher#599]
Приветствую. От одного из плагинов в один момент начались проблемы, он теряет связь с сервером и ловит её только после релоада плагина, выдавая вместе с этим ошибку связанную с authlib, после чего снова теряет связь.
Сам плагин соединяется с базой данных на внешнем сервере российском, при покупке товаров на автодонат сайте считывает покупку и выдает их. А теперь не выдает, только после релоада плагина, выдаст и потом снова уйдет на покой, хотя сам плагин продолжает работу.
Связывался с автором, говорит виновато ядро, оно хоть и paper 1.18.2, но пропатчено и имеет аутлибу стороннюю.

Лог ошибки: https://www.toptal.com/developers/hastebin/uzubulinox.md

[14:29:40 WARN]: Exception in thread "EasyPayments LongPoll Events Listener" java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'com.mojang.authlib.yggdrasil.response.Response com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)'
[14:29:40 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[14:29:40 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[14:29:40 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[14:29:40 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
[14:29:40 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[14:29:40 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[14:29:40 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[14:29:40 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[14:29:40 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[14:29:40 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:29:40 WARN]:        at EasyPayments-2.0.5.jar//ru.easydonate.easypayments.execution.processor.update.SimplePaymentEventProcessor.processUpdate(SimplePaymentEventProcessor.java:38)
[14:29:40 WARN]:        at EasyPayments-2.0.5.jar//ru.easydonate.easypayments.execution.ExecutionController.lambda$processEventUpdate$5(ExecutionController.java:272)
[14:29:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:29:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:29:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:29:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:29:40 WARN]: Caused by: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'com.mojang.authlib.yggdrasil.response.Response com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)'
[14:29:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[14:29:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[14:29:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[14:29:40 WARN]:        ... 3 more
[14:29:40 WARN]: Caused by: java.lang.NoSuchMethodError: 'com.mojang.authlib.yggdrasil.response.Response com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)'
[14:29:40 WARN]:        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:56)
[14:29:40 WARN]:        at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44)
[14:29:40 WARN]:        at net.minecraft.server.players.UserCache.a(UserCache.java:109)
[14:29:40 WARN]:        at net.minecraft.server.players.UserCache.a(UserCache.java:180)
[14:29:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.getOfflinePlayer(CraftServer.java:1812)
[14:29:40 WARN]:        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1219)
[14:29:40 WARN]:        at EasyPayments-2.0.5.jar//ru.easydonate.easypayments.easydonate4j.longpoll.data.model.EventObject.getOfflinePlayer(EventObject.java:35)
[14:29:40 WARN]:        at EasyPayments-2.0.5.jar//ru.easydonate.easypayments.execution.processor.object.NewPaymentObjectProcessor.processObject(NewPaymentObjectProcessor.java:55)
[14:29:40 WARN]:        at EasyPayments-2.0.5.jar//ru.easydonate.easypayments.execution.processor.object.NewPaymentObjectProcessor.processObject(NewPaymentObjectProcessor.java:28)
[14:29:40 WARN]:        at EasyPayments-2.0.5.jar//ru.easydonate.easypayments.execution.ExecutionController.lambda$processEventObject$6(ExecutionController.java:287)
[14:29:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:29:40 WARN]:        ... 3 more

**Comment by ccyounga** [comment]
Есть еще одна ошибка от другого плагина, не знаю связаны они или нет, я думаю что связаны, другие думают что не связаны..
Лог ошибок другого плагина: https://www.toptal.com/developers/hastebin/jezihudako.md
Этот плагин синхронизирует клиентский мод emote craft через сервер. То есть, тоже работает с подключением игроков и связью с другими ip.

**Comment by ccyounga** [comment]
Вроде решилась проблема с первым, но осталась со вторым, с этого лога: https://www.toptal.com/developers/hastebin/jezihudako.md
Если есть мысли по этому поводу, может это связано с лаунчером или launcherauthlib, подскажите, пожалуйста. Если нет, можно будет закрывать.

**Comment by gravit0** [comment]
Ваша проблема никак не связана с лаунчером. Закрыла
