### ISSUE TITLE
v5.3.0 Не запускается лаунчер при добавлении подкачки джав на клиенты. 

### ISSUE THREAD

**Issue by Engrems** [GravitLauncher/Launcher#611]
* Добавляю "javaList": {
	  "java8-windows-x86-64": "Java 8 b311 mustdie x86-64 javafx true",
	  "java8-windows-x86": "Java 8 b311 mustdie x86 javafx true",
	  "java8-linux-x86-64": "Java 8 b311 linux x86-64 javafx true",
	  "java8-linux-x86-64": "Java 8 b311 linux x86 javafx true",
	  "java8-macos-x86-64": "Java 8 b311 macos x86-64 javafx true"
	}, в JavaRuntime/config

* Потом ставлю "allowUpdates": ["java8-windows-x86-64", "java8-windows-x86", "java8-linux-x86-64", "java8-linux-x86", "java8-macos-x86-64"], в LaunchServer

* (папки на месте в updates)

* и вылазит такая вот штучка... Лаунчер не запускается от слова Совсем.

    [DEBUG] Start JavaFX Application
    Exception in Application init method
    2022.09.22 19:52:40 [ERROR] java.lang.RuntimeException: Exception in Application init method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:912)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.IllegalArgumentException: No enum constant pro.gravit.utils.helper.JVMHelper$ARCH.x86-64
        at java.lang.Enum.valueOf(Unknown Source)
        at pro.gravit.utils.helper.JVMHelper$ARCH.valueOf(Unknown Source)
        at pro.gravit.launcher.APLeNgrroihOuq.<init>(Unknown Source)
        at pro.gravit.launcher.ApLeNGEC2j0jtE.init(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
        ... 2 more

PS: не ругайте если не по формату
PPS: джавы качал архивами с oracle, 100% рабочие, да и дело до них не доходит даже.

**Comment by Engrems** [comment]
Сам спросил -- сам и отвечу :D

Дело было в том, что был включен RuntimeEncrypt. Я его выключил. Перезапустил, build и заработал лаунчер.
Сразу после - включаю RuntimeEncrypt обратно и всё продолжает быть на веселе :)
