### ISSUE TITLE
[BUGS] certificatePinning

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#613]
```
[ERROR] java.util.concurrent.ExecutionException: pro.gravit.repackage.io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at pro.gravit.launcher.BebRAcRAfTamwv.bEBraCRAFTpZPM(Unknown Source)
        at pro.gravit.launcher.BebRAcRAfTamwv.main(Unknown Source)
Caused by: pro.gravit.repackage.io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.callDecode(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.DefaultChannelPipeline.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKey(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKeys(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.run(Unknown Source)
        at pro.gravit.repackage.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
        at pro.gravit.repackage.io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.runDelegatedTasks(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.unwrap(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.decode(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(Unknown Source)
        ... 17 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
        ... 30 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 35 more
```
После истечения срока сертификата, лаунчер уже не может запуститься и самообновиться. Новый сертификат сайта в trustore закинут и новый билд работает. Но обновиться со старого уже не выйдет

**Comment by microwin7** [comment]
P.S. Если добавлять рут сертификат сайта, будет нормально, на пару лет
