### ISSUE TITLE
[BUGS] GasStation 1.7.10

### ISSUE THREAD

**Issue by Crimento** [GravitLauncher/Launcher#614]
Не запускается [GasStation](https://github.com/FalsePattern/GasStation), мод, добавляющий Mixins 0.8.5.
Клиент 1.7.10-forge, запускал без OptiFine.
Ранее использовал [MixinBooterLegacy](https://github.com/tox1cozZ/mixin-booter-legacy), но один из апдейтов [Triangulator, ныне FalseTweaks](https://github.com/FalsePattern/FalseTweaks) требует миксины 0.8.5.

Что-то реально поправить в моде или лончере, чтобы позволить обнаруживать LaunchWrapper из лончера? Мод, если что, в активной разработке, разработчик принимает PR.

Логи ниже

```
GravitLauncher (fork sashok724's Launcher) Client Launcher v5.2.11-1 stable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022.09.26 00:09:13 [WARN] JLine2 isn't in classpath, using std
2022.09.26 00:09:13 [INFO] Reading EC keypair
2022.09.26 00:09:13 [INFO] Using OAuth
2022.09.26 00:09:13 [INFO] 25.331-b09
2022.09.26 00:09:14 [INFO]  DirWatcher C:\Users\Crimento\AppData\Roaming\blackmine\updates\asset1.7.10
2022.09.26 00:09:14 [INFO]  DirWatcher C:\Users\Crimento\AppData\Roaming\blackmine\updates\test3
[00:09:15] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[00:09:15] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[00:09:15] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[00:09:15] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[00:09:15] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_331, running on Windows 11:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_331
[00:09:15] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from 00gasstation-mc1.7.10-0.3.4.jar
[00:09:15] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:09:15] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:09:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Crimento/AppData/Roaming/blackmine/updates/test3/mods/1.7.10/00gasstation-mc1.7.10-0.3.4.jar Service=LaunchWrapper Env=CLIENT
[00:09:15] [main/DEBUG]: Instantiating coremod class GasStationCore
[00:09:15] [main/INFO]: Initializing GasStationCore
[00:09:15] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterConsole:log:82]: [00:09:15] [mixin/DEBUG] Mixin bootstrap service org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapperBootstrap is not available: LaunchWrapper is not available
[00:09:15] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterConsole:log:82]: [00:09:15] [mixin/DEBUG] Catching java.util.ServiceConfigurationError:org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap not found initialising service
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap not found
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader.fail(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader.access$300(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ServiceLoader$1.next(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:151)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:143)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:169)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:179)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:87)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.falsepattern.gasstation.core.GasStationCore.<clinit>(GasStationCore.java:34)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName0(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.injectCorePlugin(MixinPlatformAgentFMLLegacy.java:241)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:168)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:154)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:74)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:142)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:103)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:118)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:166)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:99)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.BlaCKmiNeiA27B.bLACkMInE9rqUG(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.BlaCKmiNeiA27B.main(Unknown Source)
[00:09:15] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterConsole:log:93]: [00:09:15] [mixin/ERROR] No mixin host service is available. Services:  and 2 other invalid services.
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services:  and 2 other invalid services.
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:232)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:189)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:183)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:88)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.falsepattern.gasstation.core.GasStationCore.<clinit>(GasStationCore.java:34)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName0(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.injectCorePlugin(MixinPlatformAgentFMLLegacy.java:241)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:168)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:154)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:74)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:142)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:103)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:118)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:166)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:99)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.BlaCKmiNeiA27B.bLACkMInE9rqUG(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.BlaCKmiNeiA27B.main(Unknown Source)
2022.09.26 00:09:15 [ERROR] java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
Exception in thread "main" [00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: pro/gravit/launcher/blAckmInElk4Z4
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.bLAcKMINevJQhx.bLACkMInE9rqUG(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.BlaCKmiNeiA27B.bLACkMInE9rqUG(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.BlaCKmiNeiA27B.main(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: pro.gravit.launcher.blAckmInElk4Z4
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:09:15] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 3 more
Exception in thread "Thread-3" [00:09:15] [Thread-3/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: pro/gravit/repackage/io/netty/handler/codec/http/websocketx/CloseWebSocketFrame
[00:09:15] [Thread-3/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.request.websockets.ClientJSONPoint.close(Unknown Source)
[00:09:15] [Thread-3/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at pro.gravit.launcher.request.websockets.StdWebSocketService.lambda$initWebSockets$0(Unknown Source)
2022-09-26 00:09:15,444 ERROR Attempted to append to non-started appender File
Process exit code 1
```

**Comment by dimadencep** [comment]
Не используйте mixin выше 0.8.2 на версиях minecraft >1.12

**Comment by LeonusDH** [comment]
Обновлял Forge?

**Comment by Crimento** [comment]
> Обновлял Forge?

LexManos банит за одно упоминание 1.7.10 на форуме Forge :)
А новее 1614, вышедшей 7 лет назад ничего и не было

**Comment by Crimento** [comment]
> Обновлял Forge?

На ванилле, PolyMC и GDLauncher проблем нет, с кастомом вроде TLauncher проблем тоже нет, версии Forge идентичные, другие библиотеки тоже пробовал

**Comment by Crimento** [comment]
[00gasstation-mc1.7.10-0.3.4.jar.zip](https://github.com/GravitLauncher/Launcher/files/9662879/00gasstation-mc1.7.10-0.3.4.jar.zip)

Спасибо, помогло. Оставляю пофикшенный артефакт для будущих поколений, мб еще кому-то понадобится
