### ISSUE TITLE
Ошибка привязки натив при запуске под x86 бит приложением

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#640]
В dev было изменено то, чтоб выбиралась джава x64, если она есть и система такая, а лаунчер был запущен под x86
но к сожалению нативки не подтягиваются x64, приводит к остановке клиента
```
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
GravitLauncher (fork sashok724's Launcher) Client Launcher v5.3.6-1 dev
2023.02.25 23:48:22 [INFO] Successfully injected certificates to truststore
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
2023.02.25 23:48:23 [WARN] JLine2 isn't in classpath, using std
2023.02.25 23:48:23 [INFO] Reading EC keypair
2023.02.25 23:48:24 [INFO] Using OAuth
2023.02.25 23:48:24 [INFO] 25.362-b09
2023.02.25 23:48:26 [INFO]  DirWatcher C:\Users\ANTON\AppData\Roaming\OneLand\updates\asset1.7.x
2023.02.25 23:48:27 [INFO]  DirWatcher C:\Users\ANTON\AppData\Roaming\OneLand\updates\1.7.10-microwin7
[23:48:28] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:48:28] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:48:28] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[23:48:29] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[23:48:29] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_362, running on Windows 10:amd64:10.0, installed at C:\Program Files\BellSoft\LibericaJDK-8-Full\jre
[23:48:29] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_E7.jar
[23:48:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:48:29] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[23:48:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[23:48:29] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:48:29] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:48:29] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[23:48:29] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[23:48:29] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[23:48:29] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[23:48:29] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\ANTON\AppData\Roaming\OneLand\updates\1.7.10-microwin7\mods\OptiFine_1.7.10_HD_U_E7.jar
[23:48:29] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:48:33] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:48:33] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[23:48:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:48:33] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[23:48:34] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[23:48:34] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[23:48:34] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[23:48:34] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2023-02-25 23:48:35,207 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:400)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:168)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:632)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
	at net.minecraft.client.Minecraft.<clinit>(Minecraft.java:180)
	at net.minecraft.client.main.Main.main(SourceFile:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(Unknown Source)
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(Unknown Source)

[23:48:35] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_362]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.launch(Unknown Source) ~[Oneland.jar:?]
	at pro.gravit.launcher.client.ClientLauncherEntryPoint.main(Unknown Source) ~[Oneland.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Can't load C:\Users\ANTON\AppData\Roaming\OneLand\updates\1.7.10-microwin7\natives\mustdie\x86\lwjgl64.dll
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1833) ~[?:1.8.0_362]
	at java.lang.Runtime.loadLibrary0(Runtime.java:843) ~[?:1.8.0_362]
	at java.lang.System.loadLibrary(System.java:1136) ~[?:1.8.0_362]
	at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2671) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
2023.02.25 23:48:35 [ERROR] cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:48:35] [main/INFO]: [pro.gravit.launcher.utils.NativeJVMHalt:<init>:-1]: JVM exit code 0
2023.02.25 23:48:35 [INFO] WebSocket client disconnect
Process exit code 0
```

**Comment by microwin7** [comment]
![image](https://user-images.githubusercontent.com/12544425/221379681-4e15d2c0-2ca6-4fca-9a92-39bd4a7a473e.png)
Ошибка в конце только пришла в Sentry

**Comment by microwin7** [comment]
> Возможно изменения в кастомном модуле рантайма не были перенесены правильно. Проверь с чистым рантаймом

Только что дошло что рантайм обновлял до мастера, а сервер до дев 😂
