### ISSUE TITLE
Постоянные чередующиеся ошибки Don't skip Launcher Update и You are already logged in

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#642]
Про чередующиеся не шучу, каждый новый запуск то одна то вторая
Версия 5.3.6 dev
При просмотре с дебагом лаунчсеврера, создание клиента и отключение пишется как 127.0.0.1
Остальные пакеты уже с моим реальным IP
`    "ipForwarding": true,` включил на всякий, но от ошибок это меня не избавило
nginx настроен как на вики сейчас с upstream, до обновления лаунчсервера и nginx на upstream такой проблемы не было
*Часть из токена удалил*
```
2023-02-25 21:28:58.858 [epollEventLoopGroup-3-3] TRACE pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler - Message from МОЙ_IP: {"password":{"accessToken":"eyJpc3MiOiJMYXVuY2hTZXJ2ZXIiLCJzdWIiOiJtaWNyb3dpbjciLCJ1dWlkIjoiMjEwYzdhNWItNWJiNy0xMWVkLWIwOWUtMGM5ZDkyYzNlNDkwIiwiZXhwIjoxNjc3MzYzOTkxfQ","expire":0,"type":"oauth"},"auth_id":"std","getSession":false,"authType":"CLIENT","requestUUID":"5c948670-ceb1-4fa7-9a0f-3e0f33f32765","type":"auth"}
2023-02-25 21:28:58.859 [epollEventLoopGroup-3-3] TRACE pro.gravit.launchserver.socket.WebSocketService - Send to МОЙ_IP: {"error":"You are already logged in","requestUUID":"5c948670-ceb1-4fa7-9a0f-3e0f33f32765","type":"error"}
```
Команда clients:
```
21:40:01.401 [INFO ] Client name microwin7 | ip МОЙ_IP | connectUUID b14f5996-67ea-4733-8670-22742ff39deb
21:40:01.402 [INFO ] userUUID: 210c7a5b-5bb7-11ed-b09e-0c9d92c3e490
21:40:01.402 [INFO ] OAuth session pro.gravit.launchserver.auth.core.AbstractSQLCoreProvider$SQLUserSession@6d8f101c
21:40:01.402 [INFO ] Data: checkSign true | auth_id std
21:40:01.402 [INFO ] Permissions: ClientPermissions{roles=, actions=}
21:40:01.402 [INFO ] Client name microwin7 | ip МОЙ_IP | connectUUID 67b91b44-59b9-486f-81a2-43ad4c9869df
21:40:01.402 [INFO ] userUUID: 210c7a5b-5bb7-11ed-b09e-0c9d92c3e490
21:40:01.402 [INFO ] OAuth session pro.gravit.launchserver.auth.core.AbstractSQLCoreProvider$SQLUserSession@59b06924
21:40:01.402 [INFO ] Data: checkSign true | auth_id std
21:40:01.402 [INFO ] Permissions: ClientPermissions{roles=, actions=}
```
При втором запуске, картина следующая:
```
2023-02-25 21:42:33.760 [epollEventLoopGroup-3-2] TRACE pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler - New client 127.0.0.1
2023-02-25 21:42:42.690 [epollEventLoopGroup-3-2] TRACE pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler - Message from МОЙ_IP: {"requestUUID":"b16fa407-e04c-4ddd-951e-cb2e5144b23d","type":"getAvailabilityAuth"}
2023-02-25 21:42:42.690 [epollEventLoopGroup-3-2] TRACE pro.gravit.launchserver.socket.WebSocketService - Send to МОЙ_IP: {"list":[{"details":[{"type":"password"}],"name":"std","displayName":"Default","visible":true}],"features":1,"requestUUID":"b16fa407-e04c-4ddd-951e-cb2e5144b23d","type":"getAvailabilityAuth"}
2023-02-25 21:42:42.919 [epollEventLoopGroup-3-2] TRACE pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler - Message from МОЙ_IP: {"password":{"accessToken":"eyJpc3MiOiJMYXVuY2hTZXJ2ZXIiLCJzdWIiOiJtaWNyb3dpbjciLCJ1dWlkIjoiMjEwYzdhNWItNWJiNy0xMWVkLWIwOWUtMGM5ZDkyYzNlNDkwIiwiZXhwIjoxNjc3MzYzOTkxfQ","expire":0,"type":"oauth"},"auth_id":"std","getSession":false,"authType":"CLIENT","requestUUID":"7a38fb67-8a60-4552-9e20-5f4fa3ae46b3","type":"auth"}
2023-02-25 21:42:42.920 [epollEventLoopGroup-3-2] TRACE pro.gravit.launchserver.socket.WebSocketService - Send to МОЙ_IP: {"error":"Don\u0027t skip Launcher Update","requestUUID":"7a38fb67-8a60-4552-9e20-5f4fa3ae46b3","type":"error"}
```
После чего команда clients мне не показывает меня вообще, 0 совпадений по нику, IP и моему UUID

На третий раз лаунчеру уже стало плохо
```
2023.02.26 00:46:34 [ERROR] java.lang.IllegalArgumentException: Children: duplicate children added: parent = Pane[id=loginPane, styleClass=root transparent]
        at javafx.scene.Parent$2.onProposedChange(Parent.java:454)
        at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.lambda$processing$9(Unknown Source)
        at pro.gravit.launcher.client.gui.impl.ContextHelper.runInFxThreadStatic(Unknown Source)
        at pro.gravit.launcher.client.gui.impl.ContextHelper.runInFxThread(Unknown Source)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.processing(Unknown Source)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.loginWithOAuth(Unknown Source)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.tryOAuthLogin(Unknown Source)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.loginWithGui(Unknown Source)
        at pro.gravit.launcher.client.gui.impl.ContextHelper.lambda$runInFxThreadStatic$1(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)

2023.02.26 00:46:34 [DEBUG] Fxml load components/notification.fxml time: c: 132 | l: 333 | total: 465
2023.02.26 00:46:34 [INFO] Notification position: BOTTOM_RIGHT
2023.02.26 00:46:34 [INFO] X: 844.000000 Y: 531.000000
2023.02.26 00:46:34 [DEV] Send: {"password":{"accessToken":"eyJpc3MiOiJMYXVuY2hTZXJ2ZXIiLCJzdWIiOiJtaWNyb3dpbjciLCJ1dWlkIjoiMjEwYzdhNWItNWJiNy0xMWVkLWIwOWUtMGM5ZDkyYzNlNDkwIiwiZXhwIjoxNjc3MzYzOTkxfQ","expire":0,"type":"oauth"},"auth_id":"std","getSession":false,"authType":"CLIENT","requestUUID":"3b451d71-4c9d-42be-be54-a75e72cf0374","type":"auth"}
2023.02.26 00:46:34 [WARN] 2FA/MFA Password not saved
2023.02.26 00:46:35 [DEV] Message: {"error":"You are already logged in","requestUUID":"3b451d71-4c9d-42be-be54-a75e72cf0374","type":"error"}
2023.02.26 00:46:35 [ERROR] You are already logged in
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.lambda$loginWithOAuth$20(Unknown Source)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.lambda$processing$14(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:884)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at pro.gravit.launcher.request.websockets.StdWebSocketService.eventHandle(Unknown Source)
        at pro.gravit.launcher.request.websockets.ClientWebSocketService.onMessage(Unknown Source)
        at pro.gravit.launcher.request.websockets.WebSocketClientHandler.channelRead0(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.SimpleChannelInboundHandler.channelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.unwrap(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.ssl.SslHandler.decode(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.callDecode(Unknown Source)
        at pro.gravit.repackage.io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.DefaultChannelPipeline.fireChannelRead(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKey(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKeys(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.run(Unknown Source)
        at pro.gravit.repackage.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
        at pro.gravit.repackage.io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:750)

2023.02.26 00:46:35 [DEV] Processing event error
######
2023.02.26 00:50:37 [ERROR] java.lang.IllegalArgumentException: Children: duplicate children added: parent = Pane[id=layout, styleClass=transparent]
        at javafx.scene.Parent$2.onProposedChange(Parent.java:454)
        at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
        at pro.gravit.launcher.client.gui.scenes.login.LoginScene.lambda$errorHandle$15(Unknown Source)
        at pro.gravit.launcher.client.gui.impl.ContextHelper.lambda$runInFxThreadStatic$1(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:750)

```
И после чего произошёл вход в меню выборка клиента, как и во все разы выше, с этими ошибками, но логинит

clients команда меня не показывает
Четвёртый запуск показывает аналогично третьему

**Comment by microwin7** [comment]
При перелогине, ошибки нет, только после закрытия и открытия лаунчера
Допускаю конечно какую-то ошибку изменения рантайма Холдой, но такие ошибки не должны вызываться по логике, когда запрос на авторизацию то один происходит при коннекте к лаунчсерверу

**Comment by microwin7** [comment]
После отката библиотек и nginx, проблема остаётся

**Comment by microwin7** [comment]
Откат Лаунчсервера до 5.3.5 не помогал, откатил правки рантайма с 2.1.3 до 2.1.2 обратно, на кастомном модуле и проблема пропала https://github.com/GravitLauncher/LauncherRuntime/compare/v2.1.2...v2.1.3

**Comment by microwin7** [comment]
https://github.com/GravitLauncher/LauncherRuntime/commit/b04e5c27129071756cd9acf7561351a718c8d799
