### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pro.gravit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.LaunchServer)" because "this.core" is null         at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.java:66)         at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerConfig.java:182)         at pro.gravit.launchserver.LaunchServer.<init>(LaunchServer.java:167)         at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder.java:91)         at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:191)

### ISSUE THREAD

**Issue by Disxxx-vac** [GravitLauncher/Launcher#654]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pro.gravit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.LaunchServer)" because "this.core" is null
        at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.java:66)
        at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerConfig.java:182)
        at pro.gravit.launchserver.LaunchServer.<init>(LaunchServer.java:167)
        at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder.java:91)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:191)

![image](https://github.com/GravitLauncher/Launcher/assets/78232771/b30c9bea-35c3-4d93-a3a9-0326dd3948c5)

После того как стал добавлять БД, появилась данная ошибка.

**Comment by microwin7** [comment]
> Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pro.gravit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.LaunchServer)" because "this.core" is null at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.java:66) at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerConfig.java:182) at pro.gravit.launchserver.LaunchServer.(LaunchServer.java:167) at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder.java:91) at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:191)
> 
> ![image](https://user-images.githubusercontent.com/78232771/244977605-b30c9bea-35c3-4d93-a3a9-0326dd3948c5.png)
> 
> После того как стал добавлять БД, появилась данная ошибка.

Нарушена схема json для AuthCoreProvider
Необходимо: auth -> AUTH ID -> core
Читать подробнее здесь:
https://gravitlauncher.com/auth/
