### ISSUE TITLE
Ошибка Could not register mbeans

### ISSUE THREAD

**Issue by sergeyvlasenko999** [GravitLauncher/Launcher#680]
Лаунчер запускается, однако при попытке входа на сервер запуск клиента не происходит. Дебаг дает следующий лог:
`GravitLauncher (fork sashok724's Launcher) Client Launcher v5.4.4-1 stable
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
2023.09.22 23:13:52 [WARN] JLine2 isn't in classpath, using std
2023.09.22 23:13:52 [INFO] Reading EC keypair
2023.09.22 23:13:52 [INFO] Using OAuth
2023.09.22 23:13:54 [INFO]  DirWatcher C:\Users\Sergey\AppData\Roaming\StormCraft\updates\asset1.7.10
2023.09.22 23:13:54 [INFO]  DirWatcher C:\Users\Sergey\AppData\Roaming\StormCraft\updates\HiTech
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
[23:13:55] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:13:55] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:13:55] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[23:13:55] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[23:13:55] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_172, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_172
[23:13:55] [main/WARN]: The coremod da3dsoul.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:13:55] [main/INFO]: [AppEng] Core Init
[23:13:55] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
ERROR StatusConsoleListener Could not register mbeans
 java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:400)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:168)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:632)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at codechicken.core.launch.CodeChickenCorePlugin.<clinit>(CodeChickenCorePlugin.java:38)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.sToRMCraftmbU6.stoRmcRaFTAfpW(Unknown Source)
	at pro.gravit.launcher.sToRMCraftmbU6.main(Unknown Source)
[23:13:55] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2023.09.22 23:13:55 [ERROR] java.lang.SecurityException: Forbidden modification (ENTRY_DELETE, 1 times): 'C:\Users\Sergey\AppData\Roaming\StormCraft\updates\HiTech\mods\CodeChickenLib-1.7.10-1.1.3.138-universal.jar'
[23:13:55] [Client Directory Watcher/INFO]: [pro.gravit.launcher.sTorMCRaFtvZ9W:<init>:-1]: JVM exit code -123
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
ERROR StatusConsoleListener Could not register mbeans
 java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:400)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:168)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:632)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at ic2.core.coremod.IC2core.<init>(IC2core.java:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at pro.gravit.launcher.sToRMCraftmbU6.stoRmcRaFTAfpW(Unknown Source)
	at pro.gravit.launcher.sToRMCraftmbU6.main(Unknown Source)
WARN StatusConsoleListener Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
2023.09.22 23:13:55 [INFO] WebSocket client disconnect
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Process exit code -123`

Кто-то знает как сиё чудо фиксить? Искал в интернете, но варианты с модификациями файлов и настроек джавы мне не подходят, так как, очевидно, игроки не будут этим заниматься дабы зайти ко мне на сервер. Заранее спасибо

**Comment by Clercq** [comment]
поставь автоустановщик правильной java. Так можно в гравите. Гайд не подскажу тряси саппорт

**Comment by sergeyvlasenko999** [comment]
Извиняюсь за глупый вопрос, сегодня перечитал лог и увидел, что реальная причина того, что клиент не запускается в SecurityException, который ругается на CodeChickenLib. Ошибка Could not refiste mbeans хоть и появляется, но не мешает запуску клиента. Я закрываю проблему, но рекомендую разрабам все равно обратить на это внимание, так как мне лично неизвестно насколько критична эта ошибка

**Comment by sergeyvlasenko999** [comment]
Извиняюсь за глупый вопрос, сегодня перечитал лог и увидел, что реальная причина того, что клиент не запускается в SecurityException, который ругается на CodeChickenLib. Ошибка Could not refiste mbeans хоть и появляется, но не мешает запуску клиента. Я закрываю проблему, но рекомендую разрабам все равно обратить на это внимание, так как мне лично неизвестно насколько критична эта ошибка
