### ISSUE TITLE
All mirrors return error

### ISSUE THREAD

**Issue by keydevelops** [GravitLauncher/Launcher#699]
I cant download any version of game.
downloadclient 1.12.2 kerdix_test
21:17:31.556 [INFO ] Command 'downloadclient 1.12.2 kerdix_test'
21:17:31.557 [INFO ] Downloading client, it may take some time
21:17:31.558 [DEBUG] Try download https://mirror.gravitlauncher.com/5.5.x/clients/1.12.2.zip
21:17:31.933 [ERROR] Download https://mirror.gravitlauncher.com/5.5.x/clients/1.12.2.zip failed(java.io.FileNotFoundException: https://mirror.gravitlauncher.com/5.5.x/clients/1.12.2.zip)
21:17:31.935 [DEBUG] Try download https://gravit-launcher-mirror.storage.googleapis.com/clients/1.12.2.zip
21:17:32.640 [ERROR] Download https://gravit-launcher-mirror.storage.googleapis.com/clients/1.12.2.zip failed(java.io.IOException: Server returned HTTP response code: 403 for URL: https://gravit-launcher-mirror.storage.googleapis.com/clients/1.12.2.zip)
21:17:32.641 [ERROR] java.io.IOException: Error download D:\KerdixMC\updates\kerdix_test. All mirrors return error
        at pro.gravit.launchserver.manangers.MirrorManager.downloadZip(MirrorManager.java:85)
        at pro.gravit.launchserver.command.hash.DownloadClientCommand.invoke(DownloadClientCommand.java:55)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:38)
        at pro.gravit.utils.command.CommandHandler.evalNative(CommandHandler.java:29)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:19)
        at pro.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:74)
        at pro.gravit.utils.command.CommandHandler.run(CommandHandler.java:101)
        at java.base/java.lang.Thread.run(Thread.java:1583)
downloadclient 1.16.5 kerdix_vanilla
21:18:46.259 [INFO ] Command 'downloadclient 1.16.5 kerdix_vanilla'
21:18:46.261 [INFO ] Downloading client, it may take some time
21:18:46.261 [DEBUG] Try download https://mirror.gravitlauncher.com/5.5.x/clients/1.16.5.zip
21:18:46.637 [ERROR] Download https://mirror.gravitlauncher.com/5.5.x/clients/1.16.5.zip failed(java.io.FileNotFoundException: https://mirror.gravitlauncher.com/5.5.x/clients/1.16.5.zip)
21:18:46.637 [DEBUG] Try download https://gravit-launcher-mirror.storage.googleapis.com/clients/1.16.5.zip
21:18:47.367 [ERROR] Download https://gravit-launcher-mirror.storage.googleapis.com/clients/1.16.5.zip failed(java.io.IOException: Server returned HTTP response code: 403 for URL: https://gravit-launcher-mirror.storage.googleapis.com/clients/1.16.5.zip)
21:18:47.368 [ERROR] java.io.IOException: Error download D:\KerdixMC\updates\kerdix_vanilla. All mirrors return error
        at pro.gravit.launchserver.manangers.MirrorManager.downloadZip(MirrorManager.java:85)
        at pro.gravit.launchserver.command.hash.DownloadClientCommand.invoke(DownloadClientCommand.java:55)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:38)
        at pro.gravit.utils.command.CommandHandler.evalNative(CommandHandler.java:29)
        at pro.gravit.utils.command.CommandHandler.eval(CommandHandler.java:19)
        at pro.gravit.utils.command.CommandHandler.readLoop(CommandHandler.java:74)
        at pro.gravit.utils.command.CommandHandler.run(CommandHandler.java:101)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by svesnav** [comment]
С обновлением гравита на 5.5.x, сборка клиента происходит через MirrorHelper. Больше информации вы можете узнать на дискорд сервере Gravit Launcher.

Но вы также можете добавить ссылки на старое зеркало с LaucnServer.json, но лучше использовать MirrorHelper.

**Comment by microwin7** [comment]
Is not an error
Не является проблемой
