### ISSUE TITLE
IndexOutOfBoundsException в runtime

### ISSUE THREAD

**Issue by Sirse** [GravitLauncher/Launcher#91]
Проблема возникла при удалении одного из профайлов, в результате var settings.profile у некоторых игроков стал больше, чем profiles.length

https://github.com/GravitLauncher/Launcher/blob/ed7a09d2234c757dd9140d3314b3a9fbb1f5ed29/Launcher/runtime/dialog/dialog.js#L297

`Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
        at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
        at jdk.nashorn.internal.scripts.Script$Recompilation$85$9736A$^eval_.updateProfilesList(<eval>:297)
        at jdk.nashorn.internal.scripts.Script$Recompilation$80$6642A$^eval_.verifyLauncher#L:192#L:192#L:199#L:199(<eval>:203)
        at jdk.nashorn.internal.scripts.Script$Recompilation$72$1768A$^eval_.setTaskProperties#L:44(<eval>:47)
        at javafx.event.EventHandler$$NashornJavaAdapter.handle(Unknown Source)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
        at javafx.concurrent.Task.fireEvent(Task.java:1356)
        at javafx.concurrent.Task.setState(Task.java:723)
        at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1434)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)`

**Comment by gravit0** [comment]
Проблеме подвержены все, в том числе и оригинальные версии лаунчера Сашка.
Решением может быть присвоение каждому клиенту UUID

**Comment by Zaxar163** [comment]
Суть фикса: uuid = хеш имени профиля или что то подобное, вручную крайне не хочется конфиги и так здоровые.

**Comment by Sirse** [comment]
Имя профиля штука тоже не особо уникальная, надо тогда UID генерировать и писать в профайл, если его там нет.

**Comment by Zaxar163** [comment]
#100
