### ISSUE TITLE
Ошибка при запуске клиента

### ISSUE THREAD

**Issue by matrix2021** [GravitLauncher/Launcher#97]
> [05:44:40] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at ru.gravit.launcher.cV4qxWDiOooGbrAU2fqO4D0f.rCpJl2zVpUfzQFYYt668fKda(Unknown Source) [Launcher-obfed.jar:?]
	at ru.gravit.launcher.cV4qxWDiOooGbrAU2fqO4D0f.main(Unknown Source) [Launcher-obfed.jar:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 13 path $.
	at com.google.gson.Gson.fromJson(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.Gson.fromJson(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.Gson.fromJson(Unknown Source) ~[Launcher-obfed.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:116) ~[Main.class:?]
	... 8 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 13 path $.
	at com.google.gson.stream.JsonReader.beginArray(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.Gson.fromJson(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.Gson.fromJson(Unknown Source) ~[Launcher-obfed.jar:?]
	at com.google.gson.Gson.fromJson(Unknown Source) ~[Launcher-obfed.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:116) ~[Main.class:?]
	... 8 more
2018.12.08 05:44:40 [INFO] WatchService closed 2
Exception in thread "main" 2018.12.08 05:44:40 [INFO] WatchService closed 2
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ru.gravit.launcher.cV4qxWDiOooGbrAU2fqO4D0f.rCpJl2zVpUfzQFYYt668fKda(Unknown Source)
[05:44:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ru.gravit.launcher.cV4qxWDiOooGbrAU2fqO4D0f.main(Unknown Source)

Exit code 1

**Comment by Zaxar163** [comment]
Актуальность 0, виноваты конфиги.

**Comment by TheXaver** [comment]
К сожалению такая же проблема

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/92a253eb829c943c6815b3ada5b56a33d8655484
